{% set version = '2.8.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-r.utils
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/R.utils_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/R.utils/R.utils_{{ version }}.tar.gz
  sha256: cfc54dd2a7fd7f8d840f2d58615fdba1cccc3ecde325385180ff3e191acd4ac9

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  noarch: generic

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: digest (>= 0.6.10)
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-r.methodss3 >=1.7.1
    - r-r.oo >=1.22.0

  run:
    - r-base
    - r-r.methodss3 >=1.7.1
    - r-r.oo >=1.22.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('R.utils')"           # [not win]
    - "\"%R%\" -e \"library('R.utils')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/HenrikBengtsson/R.utils
  license: LGPL (>= 2.1)
  summary: Utility functions useful when programming and developing R packages.
  license_family: LGPL
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2.1'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: R.utils
# Version: 2.8.0
# Depends: R (>= 2.14.0), R.oo (>= 1.22.0)
# Imports: methods, utils, tools, R.methodsS3 (>= 1.7.1)
# Suggests: digest (>= 0.6.10)
# Title: Various Programming Utilities
# Authors@R: c(person("Henrik", "Bengtsson", role=c("aut", "cre", "cph"), email = "henrikb@braju.com"))
# Author: Henrik Bengtsson [aut, cre, cph]
# Maintainer: Henrik Bengtsson <henrikb@braju.com>
# Description: Utility functions useful when programming and developing R packages.
# License: LGPL (>= 2.1)
# LazyLoad: TRUE
# URL: https://github.com/HenrikBengtsson/R.utils
# BugReports: https://github.com/HenrikBengtsson/R.utils/issues
# RoxygenNote: 6.1.0
# NeedsCompilation: no
# Packaged: 2019-02-14 16:15:15 UTC; hb
# Repository: CRAN
# Date/Publication: 2019-02-14 21:42:21 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
