travis:
  secure:
    BINSTAR_TOKEN: F8c1lSm53UFeNSbBliqLFwJ0e3kWuvhz/sW6IIPX/Ba8dUvQjpExaHLy5p0ujsRSD05+FZOGL+SEJYZhixxepxAKhZce3tJTry1lwm2QmfhqMS8GtQmX28GDyth5XmDmb1tMl0ERCz2lqdw508Gxk8r+UEED4fuOQqvNq+u4cMXlquVJUCBo7DjOhM2p73pPfxbspllxe7P/zlaRpBgPzqdINytpdnKauzSUykS4e3ohTtkt/9V925S/WUsXfxJFdqVvGsBZgi3+rC+radyGYday4Qz5cDHqfrTaQvGJc0eGKQdGeI+1cWZQkVIwvt1kmlDm581l252GH9G1BG8pPMcr5j/hH+f6NmVBAidwkIMFBT6iNuiGhz5NhHykNgItgHcZ2WcAFDhuxTTUzwyPLxxCkLk5viElRYCMNofvP1orRFhI5iVoH/TJQrft26++0/m8e7W6g5jPTgk1sUqslBBD7qGc63zoJidZlVHS5ijdUdAmRcTE4fEiC7gVcviRklCa1ub6ig3sgm8oLWgFG3ffzPaCtfzfNalXulzAaK8vRdJUzW/fUi8j1XbRBEQ8Bl6ifVWtTztaB9r1UijLAztpSjfF1Wwxw8TEx+lPEvKlXm9St+csgzEbZ2GuTGkWb1mgP4pxEYh5shOwOY9QQLBNhGDjTwuP5bArOlYLcmI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
