travis:
  secure:
    BINSTAR_TOKEN: GU97Svt2hPaV014jnRkf5htsQks80Ujnl1RuN7hHaOeuf6YBQ26bgnL+ptkeV1upKtSZwvUYhaDBFohBE3i9+9AJX54IArWPgnAK61KlLim7eMOx+wn0HLmL47be/0vw2YfRWbk8ELMtuzlO9+05NHop3zx1JA8KlPOhIkxKjHHPWXSRAol2FOEeJ8StGIQBzuTAGrhNlM2AXcqG6irvaW5qAIn9VAFcU2DeyOrUxE1l4zZvTg+DITQZbLGMmmjbyRVBk61wNYT2kzQszMeu6ntaRTAex/AlhDR+xU7DrjmZyvt3i0kSoWDEaVCTh5RdTspgPHquSQoMQuYhlfcfBRU+pU20Nn8d6y5WFcGQQE8RiaPmFuBRtlLVznpUL1VljiLRT0me3Cw54vtAGhHU85EV9en9r4G5m3XWiRgCYC7/Rbzd6z2AfWimsteSzsYnAgcr+7YUB1FTHAq1ZRJd8ZIXtlKFil/8I6GkZTo1kWXHiDNBJOZJxTzkpQK5HRxdUSz83LIKjmo93gNZzD8ILLIGHlTvNMq8LK2aFU7q4nymaHcbBkxG5rMOVe8ouwGHfPlWhjltuzG9YNPhlSUy0Hz+L6hkBTUNzV0uw5wBw/Sjko6frIAjoCtP88wawGHDQC5vLaaZeuM0QjJiZZpcKNWQj9ZbgBVczuV+kH83iXI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
