travis:
  secure:
    BINSTAR_TOKEN: sjAfa9qZ+K66zGWd8UW3laIw4HCnw/mSvPNSLaFOQjbUqOif8P4O+r6DHd0lInNKKnOfYkCodfib5ySWAo2VPoMYZbF/afxB7VcfS1bbGm7GA3Rl4Jjuy8bsWQzxaSBETPi3ZMd9iNi4q1saRPWhSYrFGbh2/okrnlD52L8p0HH0BtRiEhjgvWu6u8lem5qz2WnRDfgbgjeVNd7HOtznon5aACDrE//jxs+GFdgfi2o9JuaAr75Wezt3w+ti4sDXeeFvB813yAs3Twn5PWBPnPTVZhXQ1KhYUZdRGQANtQvN2p/LqQmbpMxfhe+AHiIw8qYlpzF/2EfXdlneoufwqXR6ei7BoHcSeP7zysHWhxxOuZUsJ0N6dyhPLPO+eTBjBjrjZK9YH3v7VSIsEna8Kkg9KhhwYyI7wbSRHsvr7adf24wdrxibbIoGR/e8jBzAn03nHCtvhPKtJx4O6SJpPwuuGHrGSt4pAKZR1xrKKhvLa+Mo4Ro0p+2igdh/3EzDqrELxmZYOl9N1D1oRAbPByVSniUChmKm14KVl4gry6I3hwnJoFoho9cAC40z17OQJ1tWVJz0WvvAz3o0OdtMHzz0BSB4P5mHF5JCt2eR7lgD2Rkb6IeRJGzMtpdA9U0VjKnjaaqDOZf78pgWkdybdCain7VDiV/8Nb1xOSlnb2E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
