travis:
  secure:
    BINSTAR_TOKEN: Apf9N4+PC5P7clol0hjBxFqeVLdfhdSs1EzyqtNHrvFNvgFJKOxwxItt3gLvM6NeV+QgqgtaXWDxiptwtHtdC3zmXyYjo+VG+pGIwVSRYTxv0XGh1LrwHCRYIs0QbWs0fizp9E4jV3sBewex76/pjrxbJWywtKnmCcsGWsmBtGDvz7fSSO2AmimIEnhIgjGQr9tGPV355GJW1z00HImta+zH3ZrXZ3Cuyho6In9E6ImYfGfUxUC/SdveJ6cQA39tBXxexMPsYBT3j9ReerahD3Uaee0DOs9yIcGqduZle/axqwnipJI8qShatEDxbmIZlp446AikaKSy3gmhrKLcWcqIqJRAuWn9GC7GCYFu3u6rdEoiCxfAywpgD33nAJZRdy1yHW+bg8sJu13YXAPZJQ0ILIdI1tWP4QCz2Bmon6VlJMxWoJ8sJNrOMoVITnM0P/QaW5HkCKm9jfFvKNkzkrv8pU5MMek4Rg0u5RKuNfl088VO8h2C9f13KJgdSnL9B4oVjq/hFHmpBgtUUPuqKRRaGWX0oAyrTfS9+8Yy2H2ve2Ux03WkJoo9oSPzSlHxU9D4ZIchXDUfS03FDRDmW5lctLWeoJ6eCVo6tmtKpwA1pgm+pRjTu3R1GTP1XUJF2f6DEf4LN0nqvuWyncdAnEdPN9nLHRc+tbPm3t5haAE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
